#include "nsISupports.idl"

[scriptable, uuid(ce32e3ff-36f8-425f-94be-d85b26e634ee)]
interface nsIOsmozilla : nsISupports {
  void Pause();
  void Play();
  void Stop();
  void Update(in string type, in string commands);
  void QualitySwitch(in long switch_up);
};
