/* List of defines generated by configure. Included with preprocessor flag,
 * -include, to avoid long list of -D defines on the compile command-line.
 * Do not edit.
 */

#ifndef _MOZILLA_CONFIG_H_
#define _MOZILLA_CONFIG_H_

#define _WIN32 1
#define _WINDOWS 1
#define _X86_ 1
#define ACCESSIBILITY 1
#define CPP_THROW_NEW throw()
#define D_INO d_ino
#define HAVE_SNPRINTF 1
#define HW_THREADS 1
#define IBMBIDI 1
#define JS_THREADSAFE 1
#define MOZ_DEFAULT_TOOLKIT "windows"
#define MOZ_DLL_SUFFIX ".dll"
#define MOZ_ENABLE_COREXFONTS 1
#define MOZ_JSLOADER 1
#define MOZ_LOGGING 1
#define MOZ_MATHML 1
#define MOZ_PROFILESHARING 1
#define MOZ_USER_DIR ".mozilla"
#define MOZ_XPINSTALL 1
#define MOZ_XUL 1
#define MOZILLA_VERSION "1.4b"
#define NEW_H <new>
#define NO_X11 1
#define NS_PRINT_PREVIEW 1
#define NS_PRINTING 1
#define OJI 1
#define STDC_HEADERS 1
#define WIN32 1
#define WIN32_LEAN_AND_MEAN 1
#define WINVER 0x400
#define X_DISPLAY_MISSING 1
#define XP_WIN 1
#define XP_WIN32 1

#endif /* _MOZILLA_CONFIG_H_ */

