#define OHCONFIG_SHVC 1
#define OHCONFIG_ENCRYPTION 0
#define OHCONFIG_AMT 0
#define OHCONFIG_OHSTATIC 0
#define OHCONFIG_OHSHARED 1
#define OHCONFIG_AVCBASE 1
#define OHCONFIG_MOV_DEMUXER 1
#define OHCONFIG_MPEGTS_DEMUXER 1
