#!/bin/sh


xsltproc -o index.html auxiliary_files/index2html.xslt index.xml

xsltproc -o create_htmls.sh --stringparam xslt_path auxiliary_files auxiliary_files/index2sh.xslt index.xml 

chmod +x create_htmls.sh

./create_htmls.sh

