##
## Copyright : Telecom Paristech - 2011
##
## Author : Stanislas Selle 
##

###############################################################################
## Programs

COMPILER	= g++
DELETER		= rm -f


CFLAGS = -g

CFLAGS += -DXP_UNIX
CFLAGS += -fPIC

###############################################################################
## Options, Flags and LinkS

INCLUDEFLAGS =	-I/usr/include/xulrunner-lastest/ 						\
				-I../../gpac_public/include/						\
				-I../hbbtvbrowserplugin/src/				\
				-I../../gpac_public/

LIBRARYPATHS = 	-L/usr/lib/xulrunner-devel-lastest/sdk/lib/ 			\
				-L../../gpac_public/bin/gcc/						\
				-L../hbbtvbrowserplugin/bin/

LIBRARYNAMES =	-lgpac 													\
				-lmozjs 												\
				-lxpcom 												\
				-lxul 													\
				../hbbtvbrowserplugin/bin/hbbtvbrowserplugin.so


LIBRARYFLAGS = $(LIBRARYPATHS) $(LIBRARYNAMES)

FROMPKG = webkit-1.0 gtk+-2.0 pixman-1

ifneq ($(strip $(FROMPKG)),)
PKGFLAGS = `pkg-config --cflags $(FROMPKG) `
PKGLIBS = `pkg-config --libs $(FROMPKG) `
INCLUDEFLAGS += $(PKGFLAGS)
LIBRARYFLAGS += $(PKGLIBS)
endif


###############################################################################
## Files


MAINTARGET = bin/hbbtvterminal

OBJ =	obj/hbbtvterminal.o \
		obj/hbbtv_demux.o \
		obj/hbbtv_channel.o

#TESTTS = /home/selle/ressources/OpenHbbDemo-3ch2app/OpenHbbDemo-3ch2app.ts
TESTTS = /home/selle/ressources/mpeg2-ts-hbbtv/TPT/OpenHbb-ch4.ts
TESTURL = http://aquila.enst.fr:8080/subwebsite/hbbtvtest/oha0005web/index.php
TESTLOG = /tmp/test-err.txt

###############################################################################
## Rules


all : $(MAINTARGET)

$(MAINTARGET) : $(OBJ)
	$(COMPILER) $(CFLAGS) $(LIBRARYFLAGS) $(OBJ) -o $(MAINTARGET)

obj/%.o : src/%.cpp
	$(COMPILER) $(CFLAGS) $(INCLUDEFLAGS) -c $^ -o $@

test : all
	$(MAINTARGET) -input=$(TESTTS)

clean :
	rm -f $(OBJ) $(MAINTARGET)
