//{{NO_DEPENDENCIES}}
// Microsoft eMbedded Visual C++ generated include file.
// Used by Osmo4.rc
//
#define IDD_ABOUTBOX                    100
#define IDM_MENU                        101
#define IDS_EDIT                        102
#define IDS_TOOL                        103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAIN_EDIT                   105
#define IDR_MAIN_TOOL                   106
#define IDI_PAUSE                       120
#define IDD_OPT_HTTP                    121
#define IDR_MAINFRAME                   128
#define IDD_OPT_AUDIO                   129
#define IDD_OPENFILE                    130
#define IDD_CONTROL                     131
#define IDD_OPTIONS                     132
#define IDD_OPT_GEN                     133
#define IDD_OPT_RENDER                  134
#define IDD_OPT_SYSTEMS                 135
#define IDD_OPT_VIDEO                   136
#define IDI_PLAY                        137
#define IDD_OPT_FONT                    138
#define IDI_STOP                        139
#define IDD_OPT_STREAM                  140
#define IDR_MENU                        141
#define IDD_OPT_RENDER3D                142
#define IDD_OPT_DECODER                 143
#define IDC_FILELIST                    1000
#define IDC_BROWSE                      1001
#define IDC_SEEK                        1002
#define IDC_PLAY                        1003
#define IDC_STOP                        1004
#define IDC_OPT_SET_NAME                1005
#define IDC_SAVEOPT                     1006
#define IDC_LOOP                        1007
#define IDC_AUTOSTART                   1008
#define IDC_NO_CONSOLE                  1009
#define IDC_FILEASSOC                   1010
#define IDC_BIFS_RATE                   1011
#define IDC_DIRECTRENDER                1012
#define IDC_ZOOM_SCALABLE               1013
#define IDC_FAST_RENDER                 1014
#define IDC_FORCE_SIZE                  1015
#define IDC_COLOR                       1016
#define IDC_LANG                        1017
#define IDC_DEC_THREAD                  1018
#define IDC_BIFSDROP                    1019
#define IDC_FORCE_DURATION              1020
#define IDC_SLIDER                      1021
#define IDC_GD_LIST                     1022
#define IDC_AA_LIST                     1023
#define IDC_VIDEO_LIST                  1024
#define IDC_FORCE_AUDIO                 1025
#define IDC_EDIT_AUDIO                  1026
#define IDC_SPIN_AUDIO                  1027
#define IDC_AUDIO_FPS                   1028
#define IDC_SPIN_DUR                    1029
#define IDC_AUDIO_RESYNC                1030
#define IDC_DRIVER_LIST                 1031
#define IDC_FONT_LIST                   1032
#define IDC_BROWSE_FONT                 1033
#define IDC_BROWSE_CACHE                1034
#define IDC_CLEAN_CACHE                 1035
#define IDC_RESTART_CACHE               1036
#define IDC_PORT                        1037
#define IDC_RTSP                        1038
#define IDC_REORDER                     1039
#define IDC_TIMEOUT                     1040
#define IDC_BUFFER                      1041
#define IDC_REBUFFER                    1042
#define IDC_REBUFFER_LEN                1043
#define IDC_VERSION                     1044
#define IDC_AUDEC_LIST                  1046
#define IDC_VIDEC_LIST                  1047
#define IDC_COMBOSEL                    1048
#define IDC_TIME                        1049
#define IDC_ABT_TEXT                    1050
#define IDC_CTRL_PLAY                   1051
#define IDC_USE_TEXTURE                 1052
#define IDC_USE_3D_REN                  1053
#define IDC_NO_BACKCULL                 1054
#define IDC_CTRL_STOP                   1055
#define IDC_EMULATE_POW2                1056
#define IDC_WIRE_MODE                   1057
#define IDC_SAX_DURATION                1058
#define IDC_DRAW_NORMALS                1059
#define IDC_SPIN_OPT                    1060
#define IDC_AUDIO_DUR                   1061
#define IDC_SPIN_FPS                    1062
#define IDC_FILL_SCREEN                 1063
#define IDC_VIEW_FPS                    1064
#define IDC_NO_BACKLIGHT                1065
#define IDC_SAX_PROGRESSIVE             1066
#define IDC_ENABLE_LOGS                 1067
#define IDS_CAP_FILE                    32772
#define ID_FILE_RESTART                 32773
#define ID_FPS_DISP                     32774
#define IDD_CONFIGURE                   32775
#define ID_VIEW_CONTROL                 32776
#define ID_FILE_PAUSE                   32777
#define ID_FILE_STEP                    32778
#define ID_FILE_STOP                    32779
#define ID_VIEW_FULLSCREEN              32780
#define ID_FILE                         32781
#define ID_MENUITEM32789                32782
#define IDS_CAP_MENUITEM32790           32783
#define ID_VIEW                         32784
#define IDS_CAP_VIEW                    32785
#define ID_OPEN_FILE                    32786
#define ID_OPEN_URL                     32787
#define ID_SHORTCUTS                    32788
#define ID_VIEW_FIT                     32789
#define ID_NAV_NONE                     32806
#define ID_NAV_SLIDE                    32807
#define ID_NAV_RESET                    32808
#define ID_NAV_WALK                     32810
#define ID_NAV_FLY                      32811
#define ID_NAV_EXAMINE                  32812
#define ID_NAV_GRAVITY                  32813
#define ID_COLLIDE_OFF                  32815
#define ID_COLLIDE_REG                  32816
#define ID_COLLIDE_DISP                 32817
#define ID_VIEWPORT_EMPTY               32818
#define ID_NAV_HEADLIGHT                32819
#define ID_VP_0                         32820
#define ID_VP_1                         32821
#define ID_VP_2                         32822
#define ID_VP_3                         32823
#define ID_VP_4                         32824
#define ID_VP_5                         32825
#define ID_VP_6                         32826
#define ID_VP_7                         32827
#define ID_VP_8                         32828
#define ID_VP_9                         32829
#define ID_VP_10                        32830
#define ID_VP_11                        32831
#define ID_VP_12                        32832
#define ID_VP_13                        32833
#define ID_VP_14                        32834
#define ID_VP_15                        32835
#define ID_VP_16                        32836
#define ID_VP_17                        32837
#define ID_VP_18                        32838
#define ID_VP_19                        32839
#define ID_VIEW_AR_ORIG                 32890
#define ID_VIEW_AR_FILL                 32891
#define ID_VIEW_AR_43                   32892
#define ID_VIEW_AR_169                  32893
#define ID_VIEW_TIMING                  32894
#define IDS_NEW                         65000
#define IDS_FILE                        65001
#define IDS_MHELP                       65002
#define IDS_SAVE                        65003
#define IDS_CUT                         65004
#define IDS_COPY                        65005
#define IDS_PASTE                       65006
#define IDS_ABOUT                       65007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32820
#define _APS_NEXT_CONTROL_VALUE         1059
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
