.TH MP4Client 1 2019 MP4Client GPAC
.
.SH NAME
.LP
MP4Client \- GPAC command-line media player
.SH SYNOPSIS
.LP
.B MP4Client
.RI [options] \ [file]
.br
.
.SH "DESCRIPTION"
.LP
MP4Client is GPAC command-line media player. It supports all GPAC playback features (2D and 3D support, local playback, RTP streaming, HTTP faststart, many audio and video codecs ...).
.br
Specific URLs shortcuts are available, see gpac -h compositor
.
.
.SH OPTIONS
.TP
.B \-mem-track (boolean)
.br
enable memory tracker
.br
.TP
.B \-mem-track-stack (boolean)
.br
enable memory tracker with stack dumping
.br
.TP
.B \-rti (string)
.br
log run-time info (FPS, CPU, Mem usage) to given file
.br
.TP
.B \-rtix (string)
.br
same as -rti but driven by GPAC logs
.br
.TP
.B \-size (string)
.br
specifie visual size WxH? If not set, scene size or video size is used
.br
.TP
.B \-no-thread (boolean)
.br
disable thread usage (except for depending on driver audio)
.br
.TP
.B \-no-audio (boolean)
.br
disable audio
.br
.TP
.B \-pause (boolean)
.br
pause at first frame
.br
.TP
.B \-play-from (number)
.br
start playback from given time in seconds in media
.br
.TP
.B \-speed (number)
.br
start playback wit given speed
.br
.TP
.B \-loop (boolean)
.br
loop playback
.br
.TP
.B \-fs (boolean)
.br
start in fullscreen mode
.br
.TP
.B \-exit (boolean)
.br
exit when presentation is over
.br
.TP
.B \-run-for (boolean)
.br
run for indicated time in seconds and exits
.br
.TP
.B \-service (int)
.br
auto-tune to given service ID in a multiplex
.br
.TP
.B \-no-save (boolean)
.br
do not save configuration file on exit
.br
.TP
.B \-no-addon (boolean)
.br
disable automatic loading of media addons declared in source URL
.br
.TP
.B \-gui (boolean)
.br
start in GUI mode. The GUI is indicated in the configuration file [General]StartupFile
.br
.TP
.B \-ntp-shift (int)
.br
shift NTP clock of the given amount of milliseconds
.br
.TP
.B \-p (string)
.br
user-defined profile, either a name or path to an existing GPAC configuration file
.br
.TP
.B \-stats (boolean)
.br
dump filter session stats after playback
.br
.TP
.B \-graph (boolean)
.br
dump filter session graph after playback
.br
.TP
.B \-nk (boolean)
.br
disable keyboard interaction
.br
.TP
.B \-h -help (boolean)
.br
show this help. Use -hx to show expert help
.br
.TP
.B \-hc (boolean)
.br
show libgpac core options
.br
.TP
.B \-hr (boolean)
.br
show runtime options when keybard interaction is enabled
.br
.SH MP4Client runtime commands
.LP
.br
.P
.B
Prompt Interaction
.br
The following keys are used for prompt interaction:
.br
q: quit
.br
X: kill
.br
r: reload current presentation
.br
o: connect to the specified URL
.br
O: connect to the specified playlist
.br
N: switch to the next URL in the playlist. Also works with \n
.br
P: jump to a given number ahead in the playlist
.br
D: disconnect the current presentation
.br
G: select object or service ID
.br
p: play/pause the presentation
.br
s: step one frame ahead
.br
z: seek into presentation by percentage
.br
T: seek into presentation by time
.br
t: print current timing
.br
u: send a command (BIFS or LASeR) to the main scene
.br
e: evaluate JavaScript code in the main scene
.br
Z: dump current output frame to PNG
.br
w: view world info
.br
v: view list of active media objects in scene
.br
i: view Object Descriptor info (by ID)
.br
j: view Object Descriptor info (by number)
.br
b: view media objects timing and buffering info
.br
m: view media objects buffering and memory info
.br
d: dump scene graph
.br
k: turn stress mode on/off
.br
n: change navigation mode
.br
x: reset to last active viewpoint
.br
3: switch OpenGL on or off for 2D scenes
.br
4: force 4/3 Aspect Ratio
.br
5: force 16/9 Aspect Ratio
.br
6: force no Aspect Ratio (always fill screen)
.br
7: force original Aspect Ratio (default)
.br
H: set HTTP max download rate
.br
E: force reload of compositor options
.br
L: change to new log tool/level. CF MP4Client usage for possible values
.br
R: toggle run-time info display in window title bar on/off
.br
F: toggle displaying of FPS in stderr on/off
.br
f: print filter session stats
.br
g: print filter session graph
.br
h: print this message
.br
M: specify video cache memory for 2D objects ! experimental !
.br

.br
.P
.B
Content interaction
.br
It is possible to interact with content (interactive or not) using mouse and keyboard.
.br
The following commands are available:
.br
TODO
.br

.br
.SH EXAMPLES
.TP
Basic and advanced examples are available at https://github.com/gpac/gpac/wiki/mp4client
.SH MORE
.LP
Authors: GPAC developers, see git repo history (-log)
.br
For bug reports, feature requests, more information and source code, visit http://github.com/gpac/gpac
.br
build: 0.9.0-DEV-rev2539-g4b02a7f9a-filters
.br
Copyright: (c) 2000-2019 Telecom ParisTech distributed under LGPL v2.1+ - http://gpac.io
.br
.SH SEE ALSO
.LP
gpac(1), MP4Box(1)
