#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "2.4.3"
#endif /* AVUTIL_FFVERSION_H */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "2.4.3"
#endif /* AVUTIL_FFVERSION_H */
