name: ubuntu-deps
run-name: build ubuntu-deps image
on: workflow_dispatch

jobs:
    linux-image-deploy:
        runs-on: ubuntu-latest
        #if:  ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
        steps:
            - name: Check out code
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: build  image
              run: docker build -t gpac-ubuntu-deps -f build/docker/ubuntu-deps.Dockerfile .
            - name: check docker images
              run: docker image list
            - name: check docker run
              run: docker run gpac-ubuntu-deps || true
            - name: login docker hub
              run: docker login --username gpac  --password ${{secrets.DOCKER_HUB_TOKEN}}
            - name: tag docker image
              run: docker tag gpac-ubuntu-deps gpac/ubuntu-deps:latest
            - name: push docker image
              run: docker push gpac/ubuntu-deps:latest
